### ISSUE TITLE
No regex match for urls leading with "www."

### ISSUE THREAD

**Issue by ilysnemo** [Slyyxp/rsack#34] opened 2022-06-20 04:11 UTC
![image](https://user-images.githubusercontent.com/58479574/174523739-339e8a5d-30c6-4836-994f-c49db9e30f81.png)
Getting this error, the url is correct right?

**Comment by Slyyxp** [comment] 2022-06-20 04:16
The url is correct, will look into this right now and get back.

**Comment by Slyyxp** [comment] 2022-06-20 04:22
This is caused by the leading "www."

**Comment by Slyyxp** [comment] 2022-06-20 04:29
Fixed with
76be315be67666ca30a1479d9f28350ff12441f6

**Comment by ilysnemo** [comment] 2022-06-20 05:07
![image](https://user-images.githubusercontent.com/58479574/174529101-117d722b-70d2-400c-b5d2-bb998a27701b.png)
Still invalid url

**Comment by Slyyxp** [comment] 2022-06-20 05:42
I'm not sure why this doesn't match since my regex is poor.
I put a bandaid on it for now since I need to sleep. If someone can fix my regex that'd be great.
c885b52820bfe8cfd13456ed9b909b13782e2e30

In the meantime it should work with both url variants.

**Comment by ilysnemo** [comment] 2022-06-20 06:06
Ok i hope someone will fix it. Thanks sly, sleep well. Sorry for bothering you this night lol

**Comment by Slyyxp** [comment] 2022-06-20 06:10
Technically it's fixed, just not in an appropriate manner.

**Comment by ilysnemo** [comment] 2022-06-20 06:53
It still error:(
Can i have your contact? like discord or something else. It would be nice reporting the error personally, if you don;t mid

**Comment by Slyyxp** [comment] 2022-06-20 17:25
My Discord is **Slyy#3040**.

**Comment by Slyyxp** [comment] 2022-06-21 06:02
Closing this since it now functions as intended.

**Closed by Slyyxp** 2022-06-21 06:02 UTC
Labels: bug, help wanted, genie.co.kr
